### ISSUE TITLE
Auto-update fails with error

### ISSUE THREAD

**Issue by OezDur** [samuelmeuli/mini-diary#67] opened 2020-03-26 10:14 UTC
**Stack trace:**

```
Error: Redirect was cancelled
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2558:23)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
```

---

**Environment:**

```
Mini Diary 2.5.1
Electron 7.1.3
win32 10.0.18362
Locale: de
```

---

**Error description:**

Started the App after a long time (~4 months), typed in my password and got the error message.

**Comment by samuelmeuli** [comment] 2020-03-26 11:58
Duplicate of #48. Please reinstall the app.

**Closed as completed by samuelmeuli** 2020-03-26 11:58 UTC
Labels: duplicate
