### ISSUE TITLE
Error due to multiple Draft.js editors

### ISSUE THREAD

**Issue by hunny-new** [samuelmeuli/mini-diary#50] opened 2019-12-24 11:02 UTC
**Stack trace:**

```
TypeError: Cannot read property 'getIn' of undefined
    at e.exports (file:///snap/mini-diary/8/resources/app.asar/bundle/renderer.js:21:230683)
    at e.exports (file:///snap/mini-diary/8/resources/app.asar/bundle/renderer.js:21:230478)
    at e.exports (file:///snap/mini-diary/8/resources/app.asar/bundle/renderer.js:21:229215)
    at e.exports (file:///snap/mini-diary/8/resources/app.asar/bundle/renderer.js:21:228564)
    at file:///snap/mini-diary/8/resources/app.asar/bundle/renderer.js:87:98441
    at Object.m (file:///snap/mini-diary/8/resources/app.asar/bundle/renderer.js:37:1024)
    at k (file:///snap/mini-diary/8/resources/app.asar/bundle/renderer.js:37:1167)
    at file:///snap/mini-diary/8/resources/app.asar/bundle/renderer.js:37:1313
    at S (file:///snap/mini-diary/8/resources/app.asar/bundle/renderer.js:37:1399)
    at T (file:///snap/mini-diary/8/resources/app.asar/bundle/renderer.js:37:1848)
```

---

**Environment:**

```
Mini Diary 2.5.1
Electron 7.1.3
linux 5.0.0-23-generic
Locale: en-GB
```

---

**Error description:**

**Comment by samuelmeuli** [comment] 2019-12-27 11:42
Duplicate of #44

**Closed as completed by samuelmeuli** 2019-12-27 11:42 UTC
Labels: duplicate
