### ISSUE TITLE
Diary cannot be decrypted after crash

### ISSUE THREAD

**Issue by zhangyw49** [samuelmeuli/mini-diary#19] opened 2019-05-17 14:29 UTC

**Comment by zhangyw49** [comment] 2019-05-17 14:33
I'm sure I entered the correct password. But it give a message "Wrong password"

**Comment by samuelmeuli** [comment] 2019-05-17 14:43
Can you reproduce this with a new diary? If you're not using the Mac App Store version, you can change the directory in the preferences and create a new diary there.

**Comment by zhangyw49** [comment] 2019-05-18 12:31
probaly not. 
In fact, my PC reboot suddenly with a blue screen after i close diary. and now i can't open it with the correct password.
can you have any idea to recover my data?

**Comment by samuelmeuli** [comment] 2019-05-18 13:01
That's odd. Please let me know if you manage to reproduce this so I can look into why this happened.

If you have backups of your files, you can simply restore an old version of your diary file. On Windows, this file is located at `%AppData%\Mini Diary\mini-diary.txt` by default, e.g. `C:\Users\USERNAME\AppData\Mini Diary\mini-diary.txt`.

**Comment by zhangyw49** [comment] 2019-05-18 13:51
OK, I will try it when home.
and can you tell me something about how to encrypt and decrypt data?

**Comment by samuelmeuli** [comment] 2019-05-18 14:11
When you enter your password in Mini Diary, the app [hashes it](https://github.com/samuelmeuli/mini-diary/blob/47405451d357f6a588dad2ab84dc50aaa8bc9808/src/renderer/files/diary/hashPassword.ts#L9-L16) and uses the resulting string to [decrypt](https://github.com/samuelmeuli/mini-diary/blob/47405451d357f6a588dad2ab84dc50aaa8bc9808/src/renderer/files/fileAccess.ts#L27-L32) and [encrypt](https://github.com/samuelmeuli/mini-diary/blob/47405451d357f6a588dad2ab84dc50aaa8bc9808/src/renderer/files/fileAccess.ts#L38-L46) your diary file.

**Comment by zhangyw49** [comment] 2019-05-19 00:52
I think i lose my data forever. is the hashedpassword cracked? and where is the hashedpassword stored?

**Comment by zhangyw49** [comment] 2019-05-19 01:39
i open mini-diary.txt with editor. there are all 0000 now

**Comment by zhangyw49** [comment] 2019-05-19 05:16
the content mini-diary.txt is all 0000s now.
is it still can be recovered?

**Comment by samuelmeuli** [comment] 2019-05-19 18:56
Sorry to hear that. If you don't have any backups, you won't be able to recover the data if your file is corrupted.

I'll think about adding an auto-backup mechanism to the app which backs up your data e.g. once a day.

**Comment by unpilbaek** [comment] 2019-08-03 01:01
Hello, I have experienced a similar problem. I have downloaded the Mac App Store version, and when I turned on my laptop again, even after entering a correct password the app keeps giving a message "Wrong password". I deleted the app and re-installed the app, hoping that would fix the issue, but the app would just keep asking me to enter the password. I was also not able to find the functionality for changing passwords.

Also, the auto-backup functionality sounds awesome. Do you know when would that functionality be added to the Mac App Store version?

**Comment by samuelmeuli** [comment] 2019-08-03 08:40
@unpilbaek Thanks for reporting this.

The MAS app stores its data at `/Users/YOURUSERNAME/Library/Containers/com.samuelmeuli.minidiary/Data/Library/Application Support/Mini Diary/`. The backups can also be found there. If you replace your `mini-diary.txt` file with one of the backups, close and re-open the app, you might be able to decrypt the diary again.

It really sounds like there is some operation that corrupts the diary file, or encrypts it with the wrong password (maybe an empty string). Do you remember how you left the app before reopening it? Did you close it normally, did it crash, did your computer go to sleep, ...?

**Comment by unpilbaek** [comment] 2019-08-03 19:11
Hello Samneul Meuli,

I wasn’t able to find the directory that you suggested, but I did manage to get into the contents of Mini Diary through the Applications folder in Mac. Unfortunately, I am not sure how to locate the backup files from the package contents.

And I believe my computer was fully depleted of battery with the application open. When I re-charged the device and attempted to open the app, it kept telling me that the correct password I input was the wrong one.

Thanks,
Unpil Baek

**Comment by samuelmeuli** [comment] 2019-08-04 15:23
Thanks for the info, I'll look into it.

The data isn't in the application package, it's in the Library folder at the path above. The Library folder is hidden by default (see [this guide](http://osxdaily.com/2016/12/12/show-user-library-folder-macos-sierra/) on how to find it). Also, make sure to replace `YOURUSERNAME` with your actual username. Let me know if this works for you :)

**Comment by samuelmeuli** [comment] 2020-02-06 15:19
Haven't received any new reports of this issue, so I'm going to close this.

**Closed as completed by samuelmeuli** 2020-02-06 15:19 UTC
Labels: bug

**Comment by laantones** [comment] 2021-03-12 10:24
Does the non-MAS version also perform auto-backups? If so, where are these stored? My diary seems to be 0 bytes all of a sudden and my last manual backup was a few weeks ago.
