### ISSUE TITLE
Auto-update fails with error

### ISSUE THREAD

**Issue by ghost** [samuelmeuli/mini-diary#52] opened 2020-01-02 17:21 UTC
**Stack trace:**

```
Error: Redirect was cancelled
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2561:23)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
```

---

**Environment:**

```
Mini Diary 2.5.2
Electron 7.1.7
darwin 19.2.0
Locale: en-US
```

---

**Error description:**

**Comment by samuelmeuli** [comment] 2020-01-02 17:35
Duplicate of #48

**Closed as completed by samuelmeuli** 2020-01-02 17:35 UTC
Labels: duplicate
